name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g allure-commandline

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run tests (pytest.ini already has allure opts)
        run: pytest -m smoke tests/

      - name: Generate Allure Report
        run: allure generate allure-results -o public/allure --clean

      - name: Generate Playwright Trace Viewer
        run: |
          mkdir -p public/traces
          export TRACE_DIR_NAME="run-$(date +'%Y-%m-%d')"
          mkdir -p public/traces/$TRACE_DIR_NAME
          TRACE_FILE=$(find artifacts/traces -name 'trace-*.zip' | head -n 1)
          npx playwright show-trace $TRACE_FILE --save-as public/traces/$TRACE_DIR_NAME

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
