name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g allure-commandline

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run tests (pytest.ini already has allure opts)
        run: pytest -m smoke tests/

      - name: Generate Allure Report
        run: allure generate allure-results -o public/allure --clean

      - name: Generate Playwright Trace Viewer
        run: |
          npm install -g @playwright/test
          export TRACE_DIR_NAME="run-$(date +'%Y-%m-%d')"
          mkdir -p public/traces/$TRACE_DIR_NAME

          # Copy viewer UI
          cp -r node_modules/@playwright/test/lib/traceViewer public/traces/$TRACE_DIR_NAME/traceViewer

          # Copy all traces
          cp artifacts/traces/*.zip public/traces/$TRACE_DIR_NAME/

          # Generate index.html for each trace
          for TRACE_FILE in artifacts/traces/trace-*.zip; do
            BASENAME=$(basename "$TRACE_FILE")
            TRACE_NAME="${BASENAME%.zip}"

            TRACE_HTML="public/traces/$TRACE_DIR_NAME/${TRACE_NAME}.html"

            cat <<EOF > $TRACE_HTML
          <!DOCTYPE html>
          <html>
          <head><meta charset="UTF-8"><title>${TRACE_NAME}</title></head>
          <body style="margin:0">
          <iframe src="traceViewer/index.html?trace=${BASENAME}" width="100%" height="100%" style="border:none"></iframe>
          </body>
          </html>
          EOF
          done

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
