name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g allure-commandline

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run tests
        run: pytest -m smoke tests/

      - name: Generate Allure Report
        run: allure generate allure-results -o public/allure --clean

      - name: Generate Playwright Trace Viewer
        run: |
          npm install --no-save playwright-core

          export TRACE_DIR_NAME="latest"
          mkdir -p public/traces/$TRACE_DIR_NAME

          # Copy TraceViewer UI
          VIEWER_PATH=$(find node_modules -type d -name traceViewer | head -n 1)
          cp -r "$VIEWER_PATH" public/traces/$TRACE_DIR_NAME/traceViewer

          # Copy trace zips
          cp artifacts/traces/*.zip public/traces/$TRACE_DIR_NAME/ || echo "No trace zip files found"

          # Generate HTML index page
          INDEX_HTML="public/traces/$TRACE_DIR_NAME/index.html"
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Traces</title></head><body><h1>Playwright Traces</h1><ul>" > "$INDEX_HTML"

          # Loop over each .zip and generate an iframe page
          for TRACE_FILE in public/traces/$TRACE_DIR_NAME/trace_*.zip; do
            [ -e "$TRACE_FILE" ] || continue
            BASENAME=$(basename "$TRACE_FILE")
            echo "Processing $BASENAME"
            TRACE_NAME="${BASENAME%.zip}"
            TRACE_HTML="public/traces/$TRACE_DIR_NAME/${TRACE_NAME}.html"
            TRACE_IFRAME_PATH="traceViewer/index.html?trace=${BASENAME}"

            # Generate the HTML page for the trace
            cat <<EOF > "$TRACE_HTML"
          <!DOCTYPE html>
          <html>
            <head><meta charset="UTF-8"><title>${TRACE_NAME}</title></head>
            <body style="margin:0">
              <iframe src="${TRACE_IFRAME_PATH}" width="100%" height="100%" style="border:none"></iframe>
            </body>
          </html>
          EOF

            # Add link to index
            echo "<li><a href=\"${TRACE_NAME}.html\">${TRACE_NAME}</a></li>" >> "$INDEX_HTML"
          done

          echo "</ul></body></html>" >> "$INDEX_HTML"

      - name: Deploy Allure Report and Traces to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
# https://shukal94.github.io/pwtracing/traces/latest/traceViewer/index.html?trace=https://shukal94.github.io/pwtracing/traces/latest/trace_test_get_started_link_5b8cf0c31f6148fdbb3d00d1b2be0a35.zip
